services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    restart: always

  odoo:
    image: odoo:16  # Stable version for API development
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons  # This links your local code to the container
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
      - ADDONS_PATH=/mnt/extra-addons
    restart: always

volumes:
  odoo-db-data:
  odoo-web-data:
